// import './utils/dota_ts_adapter';
// import './modules/custom_base_modifier';
import './modules/hero_icon_list';
import './modules/hero_items';
import './utils/dota_ts_adapter';
import './UtilityFunctions';
import './modules/extends/extends_origin_client';
import './modules/particle/particle_list';
import './common_modifier/index';
// globalThis.HeroParticleList = {};
// globalThis.GeneircParticleList = {};
// globalThis.HeroParticleList = {};
// globalThis.AvatarHeroParticleList = {};
// globalThis.ItemParticleList = {};
// globalThis.AvatarItemParticleList = {};
// globalThis.UnitParticleList = {};
DebugPrint('Client script loaded!');
