// import './utils/dota_ts_adapter';
// import './modules/custom_base_modifier';
import './utils/dota_ts_adapter';
import './UtilityFunctions';
import './common_modifier/index';
// globalThis.HeroParticleList = {};
// globalThis.GeneircParticleList = {};
// globalThis.HeroParticleList = {};
// globalThis.AvatarHeroParticleList = {};
// globalThis.ItemParticleList = {};
// globalThis.AvatarItemParticleList = {};
// globalThis.UnitParticleList = {};
DebugPrint('Client script loaded!');
