/** 类型-英雄名的标准格式 */
declare type HeroNameFormat = `npc_dota_hero${string}`;
/** 类型-物品名的标准格式 */
declare type ItemNameFormat = `item_${string}`;
/** 类型-modifier名的标准格式 */
declare type ModifierNameFormat = `modifier_${string}`;
/** Dota原生技能 */
declare const enum DotaAbility {
    /** 法力损毁 */
    antimage_mana_break = 'antimage_mana_break',
    /** 闪烁 */
    antimage_blink = 'antimage_blink',
    /** 友军法术反制 */
    antimage_counterspell_ally = 'antimage_counterspell_ally',
    /** 法术反制 */
    antimage_counterspell = 'antimage_counterspell',
    /** 法力虚空 */
    antimage_mana_void = 'antimage_mana_void',
    /** 闪烁碎片 */
    antimage_mana_overload = 'antimage_mana_overload',
    /** 暗影突袭 */
    queenofpain_shadow_strike = 'queenofpain_shadow_strike',
    /** 闪烁 */
    queenofpain_blink = 'queenofpain_blink',
    /** 痛苦尖叫 */
    queenofpain_scream_of_pain = 'queenofpain_scream_of_pain',
    /** 超声冲击波 */
    queenofpain_sonic_wave = 'queenofpain_sonic_wave',
    /** 龙破斩 */
    lina_dragon_slave = 'lina_dragon_slave',
    /** 光击阵 */
    lina_light_strike_array = 'lina_light_strike_array',
    /** 炽魂 */
    lina_fiery_soul = 'lina_fiery_soul',
    /** 神灭斩 */
    lina_laguna_blade = 'lina_laguna_blade',
    /** 腾焰斗篷 */
    lina_flame_cloak = 'lina_flame_cloak',
    /** 月神之箭 */
    mirana_arrow = 'mirana_arrow',
    /** 月之暗面 */
    mirana_invis = 'mirana_invis',
    /** 跳跃 */
    mirana_leap = 'mirana_leap',
    /** 群星风暴 */
    mirana_starfall = 'mirana_starfall',
    /** 狂暴 */
    life_stealer_rage = 'life_stealer_rage',
    /** 盛宴 */
    life_stealer_feast = 'life_stealer_feast',
    /** 尸鬼狂怒 */
    life_stealer_ghoul_frenzy = 'life_stealer_ghoul_frenzy',
    /** 撕裂伤口 */
    life_stealer_open_wounds = 'life_stealer_open_wounds',
    /** 感染 */
    life_stealer_infest = 'life_stealer_infest',
    /** 吞灭 */
    life_stealer_consume = 'life_stealer_consume',
    /** 发芽 */
    furion_sprout = 'furion_sprout',
    /** 传送 */
    furion_teleportation = 'furion_teleportation',
    /** 自然的呼唤 */
    furion_force_of_nature = 'furion_force_of_nature',
    /** 青森诅咒 */
    furion_curse_of_the_forest = 'furion_curse_of_the_forest',
    /** 自然之怒 */
    furion_wrath_of_nature = 'furion_wrath_of_nature',
    /** 集中火力 */
    windrunner_focusfire = 'windrunner_focusfire',
    /** 强力击 */
    windrunner_powershot = 'windrunner_powershot',
    /** 束缚击 */
    windrunner_shackleshot = 'windrunner_shackleshot',
    /** 风行 */
    windrunner_windrun = 'windrunner_windrun',
    /** 狂风之力 */
    windrunner_gale_force = 'windrunner_gale_force',
    /** 裂地尖刺 */
    lion_impale = 'lion_impale',
    /** 妖术 */
    lion_voodoo = 'lion_voodoo',
    /** 法力吸取 */
    lion_mana_drain = 'lion_mana_drain',
    /** 死亡之指 */
    lion_finger_of_death = 'lion_finger_of_death',
    /** 魔法箭 */
    vengefulspirit_magic_missile = 'vengefulspirit_magic_missile',
    /** 恐怖波动 */
    vengefulspirit_wave_of_terror = 'vengefulspirit_wave_of_terror',
    /** 复仇光环 */
    vengefulspirit_command_aura = 'vengefulspirit_command_aura',
    /** 移形换位 */
    vengefulspirit_nether_swap = 'vengefulspirit_nether_swap',
    /** 麻痹药剂 */
    witch_doctor_paralyzing_cask = 'witch_doctor_paralyzing_cask',
    /** 巫毒疗法 */
    witch_doctor_voodoo_restoration = 'witch_doctor_voodoo_restoration',
    /** 巫蛊咒术 */
    witch_doctor_maledict = 'witch_doctor_maledict',
    /** 死亡守卫 */
    witch_doctor_death_ward = 'witch_doctor_death_ward',
    /** 巫毒变身术 */
    witch_doctor_voodoo_switcheroo = 'witch_doctor_voodoo_switcheroo',
    /** 撕裂大地 */
    leshrac_split_earth = 'leshrac_split_earth',
    /** 恶魔敕令 */
    leshrac_diabolic_edict = 'leshrac_diabolic_edict',
    /** 闪电风暴 */
    leshrac_lightning_storm = 'leshrac_lightning_storm',
    /** 虚无主义 */
    leshrac_greater_lightning_storm = 'leshrac_greater_lightning_storm',
    /** 脉冲新星 */
    leshrac_pulse_nova = 'leshrac_pulse_nova',
    /** 剑刃风暴 */
    juggernaut_blade_fury = 'juggernaut_blade_fury',
    /** 治疗守卫 */
    juggernaut_healing_ward = 'juggernaut_healing_ward',
    /** 剑舞 */
    juggernaut_blade_dance = 'juggernaut_blade_dance',
    /** 无敌斩 */
    juggernaut_omni_slash = 'juggernaut_omni_slash',
    /** 迅风斩 */
    juggernaut_swift_slash = 'juggernaut_swift_slash',
    /** 肉钩 */
    pudge_meat_hook = 'pudge_meat_hook',
    /** 腐烂 */
    pudge_rot = 'pudge_rot',
    /** 腐肉堆积 */
    pudge_flesh_heap = 'pudge_flesh_heap',
    /** 肢解 */
    pudge_dismember = 'pudge_dismember',
    /** 倾吐 */
    pudge_eject = 'pudge_eject',
    /** 虚弱 */
    bane_enfeeble = 'bane_enfeeble',
    /** 蚀脑 */
    bane_brain_sap = 'bane_brain_sap',
    /** 噩梦 */
    bane_nightmare = 'bane_nightmare',
    /** 噩梦终止 */
    bane_nightmare_end = 'bane_nightmare_end',
    /** 魔爪 */
    bane_fiends_grip = 'bane_fiends_grip',
    /** 沟壑 */
    earthshaker_fissure = 'earthshaker_fissure',
    /** 强化图腾 */
    earthshaker_enchant_totem = 'earthshaker_enchant_totem',
    /** 余震 */
    earthshaker_aftershock = 'earthshaker_aftershock',
    /** 回音击 */
    earthshaker_echo_slam = 'earthshaker_echo_slam',
    /** 掘地穿刺 */
    sandking_burrowstrike = 'sandking_burrowstrike',
    /** 沙尘暴 */
    sandking_sand_storm = 'sandking_sand_storm',
    /** 腐尸毒 */
    sandking_caustic_finale = 'sandking_caustic_finale',
    /** 地震 */
    sandking_epicenter = 'sandking_epicenter',
    /** 毁灭阴影 */
    nevermore_shadowraze1 = 'nevermore_shadowraze1',
    /** 毁灭阴影 */
    nevermore_shadowraze2 = 'nevermore_shadowraze2',
    /** 毁灭阴影 */
    nevermore_shadowraze3 = 'nevermore_shadowraze3',
    /** 支配死灵 */
    nevermore_necromastery = 'nevermore_necromastery',
    /** 魔王降临 */
    nevermore_dark_lord = 'nevermore_dark_lord',
    /** 魂之挽歌 */
    nevermore_requiem = 'nevermore_requiem',
    /** 风暴之拳 */
    sven_storm_bolt = 'sven_storm_bolt',
    /** 巨力挥舞 */
    sven_great_cleave = 'sven_great_cleave',
    /** 战吼 */
    sven_warcry = 'sven_warcry',
    /** 神之力量 */
    sven_gods_strength = 'sven_gods_strength',
    /** 窒碍短匕 */
    phantom_assassin_stifling_dagger = 'phantom_assassin_stifling_dagger',
    /** 幻影突袭 */
    phantom_assassin_phantom_strike = 'phantom_assassin_phantom_strike',
    /** 魅影无形 */
    phantom_assassin_blur = 'phantom_assassin_blur',
    /** 恩赐解脱 */
    phantom_assassin_coup_de_grace = 'phantom_assassin_coup_de_grace',
    /** 刀阵旋风 */
    phantom_assassin_fan_of_knives = 'phantom_assassin_fan_of_knives',
    /** 冥火爆击 */
    skeleton_king_hellfire_blast = 'skeleton_king_hellfire_blast',
    /** 吸血灵魂 */
    skeleton_king_vampiric_aura = 'skeleton_king_vampiric_aura',
    /** 本命一击 */
    skeleton_king_mortal_strike = 'skeleton_king_mortal_strike',
    /** 绝冥再生 */
    skeleton_king_reincarnation = 'skeleton_king_reincarnation',
    /** 霜冻之箭 */
    drow_ranger_frost_arrows = 'drow_ranger_frost_arrows',
    /** 数箭齐发 */
    drow_ranger_multishot = 'drow_ranger_multishot',
    /** 狂风 */
    drow_ranger_wave_of_silence = 'drow_ranger_wave_of_silence',
    /** 射手天赋 */
    drow_ranger_marksmanship = 'drow_ranger_marksmanship',
    /** 冰川 */
    drow_ranger_glacier = 'drow_ranger_glacier',
    /** 波浪形态 */
    morphling_waveform = 'morphling_waveform',
    /** 变体打击（敏捷） */
    morphling_adaptive_strike_agi = 'morphling_adaptive_strike_agi',
    /** 变体打击（力量） */
    morphling_adaptive_strike_str = 'morphling_adaptive_strike_str',
    /** 属性变换（敏捷获取） */
    morphling_morph_agi = 'morphling_morph_agi',
    /** 属性变换（力量获取） */
    morphling_morph_str = 'morphling_morph_str',
    /** 变形 */
    morphling_replicate = 'morphling_replicate',
    /** 替换复制体 */
    morphling_morph_replicate = 'morphling_morph_replicate',
    /** 血怒 */
    bloodseeker_bloodrage = 'bloodseeker_bloodrage',
    /** 血祭 */
    bloodseeker_blood_bath = 'bloodseeker_blood_bath',
    /** 焦渴 */
    bloodseeker_thirst = 'bloodseeker_thirst',
    /** 割裂 */
    bloodseeker_rupture = 'bloodseeker_rupture',
    /** 血雾 */
    bloodseeker_blood_mist = 'bloodseeker_blood_mist',
    /** 狂战士之吼 */
    axe_berserkers_call = 'axe_berserkers_call',
    /** 战斗饥渴 */
    axe_battle_hunger = 'axe_battle_hunger',
    /** 反击螺旋 */
    axe_counter_helix = 'axe_counter_helix',
    /** 淘汰之刃 */
    axe_culling_blade = 'axe_culling_blade',
    /** 灵魂之矛 */
    phantom_lancer_spirit_lance = 'phantom_lancer_spirit_lance',
    /** 神行百变 */
    phantom_lancer_doppelwalk = 'phantom_lancer_doppelwalk',
    /** 幻影冲锋 */
    phantom_lancer_phantom_edge = 'phantom_lancer_phantom_edge',
    /** 并列 */
    phantom_lancer_juxtapose = 'phantom_lancer_juxtapose',
    /** 等离子场 */
    razor_plasma_field = 'razor_plasma_field',
    /** 静电连接 */
    razor_static_link = 'razor_static_link',
    /** 风暴涌动 */
    razor_unstable_current = 'razor_unstable_current',
    /** 风暴之眼 */
    razor_eye_of_the_storm = 'razor_eye_of_the_storm',
    /** 残影 */
    storm_spirit_static_remnant = 'storm_spirit_static_remnant',
    /** 电子涡流 */
    storm_spirit_electric_vortex = 'storm_spirit_electric_vortex',
    /** 超负荷 */
    storm_spirit_overload = 'storm_spirit_overload',
    /** 球状闪电 */
    storm_spirit_ball_lightning = 'storm_spirit_ball_lightning',
    /** 冰霜新星 */
    crystal_maiden_crystal_nova = 'crystal_maiden_crystal_nova',
    /** 冰封禁制 */
    crystal_maiden_frostbite = 'crystal_maiden_frostbite',
    /** 奥术光环 */
    crystal_maiden_brilliance_aura = 'crystal_maiden_brilliance_aura',
    /** 极寒领域 */
    crystal_maiden_freezing_field = 'crystal_maiden_freezing_field',
    /** 停止极寒领域 */
    crystal_maiden_freezing_field_stop = 'crystal_maiden_freezing_field_stop',
    /** 冰晶克隆 */
    crystal_maiden_crystal_clone = 'crystal_maiden_crystal_clone',
    /** 洪流 */
    kunkka_torrent = 'kunkka_torrent',
    /** 洪流浪潮 */
    kunkka_torrent_storm = 'kunkka_torrent_storm',
    /** 潮汐使者 */
    kunkka_tidebringer = 'kunkka_tidebringer',
    /** x标记 */
    kunkka_x_marks_the_spot = 'kunkka_x_marks_the_spot',
    /** 送回 */
    kunkka_return = 'kunkka_return',
    /** 幽灵船 */
    kunkka_ghostship = 'kunkka_ghostship',
    /** 潮汐波 */
    kunkka_tidal_wave = 'kunkka_tidal_wave',
    /** 致命连接 */
    warlock_fatal_bonds = 'warlock_fatal_bonds',
    /** 暗言术 */
    warlock_shadow_word = 'warlock_shadow_word',
    /** 剧变 */
    warlock_upheaval = 'warlock_upheaval',
    /** 混乱之祭 */
    warlock_rain_of_chaos = 'warlock_rain_of_chaos',
    /** 弧形闪电 */
    zuus_arc_lightning = 'zuus_arc_lightning',
    /** 雷击 */
    zuus_lightning_bolt = 'zuus_lightning_bolt',
    /** 雷神之怒 */
    zuus_thundergods_wrath = 'zuus_thundergods_wrath',
    /** 雷云 */
    zuus_cloud = 'zuus_cloud',
    /** 神圣一跳 */
    zuus_heavenly_jump = 'zuus_heavenly_jump',
    /** 霹雳之手 */
    zuus_lightning_hands = 'zuus_lightning_hands',
    /** 山崩 */
    tiny_avalanche = 'tiny_avalanche',
    /** 投掷 */
    tiny_toss = 'tiny_toss',
    /** 抓树 */
    tiny_tree_grab = 'tiny_tree_grab',
    /** 扔树 */
    tiny_toss_tree = 'tiny_toss_tree',
    /** 长大 */
    tiny_grow = 'tiny_grow',
    /** 树木连掷 */
    tiny_tree_channel = 'tiny_tree_channel',
    /** 幻象法球 */
    puck_illusory_orb = 'puck_illusory_orb',
    /** 新月之痕 */
    puck_waning_rift = 'puck_waning_rift',
    /** 相位转移 */
    puck_phase_shift = 'puck_phase_shift',
    /** 梦境缠绕 */
    puck_dream_coil = 'puck_dream_coil',
    /** 灵动之翼 */
    puck_ethereal_jaunt = 'puck_ethereal_jaunt',
    /** 剧毒之触 */
    dazzle_poison_touch = 'dazzle_poison_touch',
    /** 薄葬 */
    dazzle_shallow_grave = 'dazzle_shallow_grave',
    /** 暗影波 */
    dazzle_shadow_wave = 'dazzle_shadow_wave',
    /** 邪能 */
    dazzle_bad_juju = 'dazzle_bad_juju',
    /** 弹幕冲击 */
    rattletrap_battery_assault = 'rattletrap_battery_assault',
    /** 能量齿轮 */
    rattletrap_power_cogs = 'rattletrap_power_cogs',
    /** 照明火箭 */
    rattletrap_rocket_flare = 'rattletrap_rocket_flare',
    /** 发射钩爪 */
    rattletrap_hookshot = 'rattletrap_hookshot',
    /** 超速运转 */
    rattletrap_overclocking = 'rattletrap_overclocking',
    /** 喷气背包 */
    rattletrap_jetpack = 'rattletrap_jetpack',
    /** 寒霜爆发 */
    lich_frost_nova = 'lich_frost_nova',
    /** 阴邪凝视 */
    lich_sinister_gaze = 'lich_sinister_gaze',
    /** 冰霜魔盾 */
    lich_frost_shield = 'lich_frost_shield',
    /** 连环霜冻 */
    lich_chain_frost = 'lich_chain_frost',
    /** 寒冰尖柱 */
    lich_ice_spire = 'lich_ice_spire',
    /** 巨浪 */
    tidehunter_gush = 'tidehunter_gush',
    /** 海妖外壳 */
    tidehunter_kraken_shell = 'tidehunter_kraken_shell',
    /** 锚击 */
    tidehunter_anchor_smash = 'tidehunter_anchor_smash',
    /** 毁灭 */
    tidehunter_ravage = 'tidehunter_ravage',
    /** 重如铁锚 */
    tidehunter_dead_in_the_water = 'tidehunter_dead_in_the_water',
    /** 苍穹震击 */
    shadow_shaman_ether_shock = 'shadow_shaman_ether_shock',
    /** 妖术 */
    shadow_shaman_voodoo = 'shadow_shaman_voodoo',
    /** 枷锁 */
    shadow_shaman_shackles = 'shadow_shaman_shackles',
    /** 群蛇守卫 */
    shadow_shaman_mass_serpent_ward = 'shadow_shaman_mass_serpent_ward',
    /** 烟幕 */
    riki_smoke_screen = 'riki_smoke_screen',
    /** 刀光谍影 */
    riki_backstab = 'riki_backstab',
    /** 闪烁突袭 */
    riki_blink_strike = 'riki_blink_strike',
    /** 绝杀秘技 */
    riki_tricks_of_the_trade = 'riki_tricks_of_the_trade',
    /** 憎恶 */
    enigma_malefice = 'enigma_malefice',
    /** 恶魔召唤 */
    enigma_demonic_conversion = 'enigma_demonic_conversion',
    /** 午夜凋零 */
    enigma_midnight_pulse = 'enigma_midnight_pulse',
    /** 黑洞 */
    enigma_black_hole = 'enigma_black_hole',
    /** 激光 */
    tinker_laser = 'tinker_laser',
    /** 热导飞弹 */
    tinker_heat_seeking_missile = 'tinker_heat_seeking_missile',
    /** 折跃耀光 */
    tinker_warp_grenade = 'tinker_warp_grenade',
    /** 再装填 */
    tinker_rearm = 'tinker_rearm',
    /** 防御矩阵 */
    tinker_defense_matrix = 'tinker_defense_matrix',
    /** 基恩载具 */
    tinker_keen_teleport = 'tinker_keen_teleport',
    /** 榴霰弹 */
    sniper_shrapnel = 'sniper_shrapnel',
    /** 爆头 */
    sniper_headshot = 'sniper_headshot',
    /** 瞄准 */
    sniper_take_aim = 'sniper_take_aim',
    /** 暗杀 */
    sniper_assassinate = 'sniper_assassinate',
    /** 震荡手雷 */
    sniper_concussive_grenade = 'sniper_concussive_grenade',
    /** 死亡脉冲 */
    necrolyte_death_pulse = 'necrolyte_death_pulse',
    /** 竭心光环 */
    necrolyte_heartstopper_aura = 'necrolyte_heartstopper_aura',
    /** 幽魂护罩 */
    necrolyte_sadist = 'necrolyte_sadist',
    /** 死神镰刀 */
    necrolyte_reapers_scythe = 'necrolyte_reapers_scythe',
    /** 死亡搜寻 */
    necrolyte_death_seeker = 'necrolyte_death_seeker',
    /** 守卫冲刺 */
    slardar_sprint = 'slardar_sprint',
    /** 鱼人碎击 */
    slardar_slithereen_crush = 'slardar_slithereen_crush',
    /** 深海重击 */
    slardar_bash = 'slardar_bash',
    /** 侵蚀雾霭 */
    slardar_amplify_damage = 'slardar_amplify_damage',
    /** 野性之斧 */
    beastmaster_wild_axes = 'beastmaster_wild_axes',
    /** 野性呼唤豪猪 */
    beastmaster_call_of_the_wild_boar = 'beastmaster_call_of_the_wild_boar',
    /** 野性呼唤战鹰 */
    beastmaster_call_of_the_wild_hawk = 'beastmaster_call_of_the_wild_hawk',
    /** 野性之心 */
    beastmaster_inner_beast = 'beastmaster_inner_beast',
    /** 原始咆哮 */
    beastmaster_primal_roar = 'beastmaster_primal_roar',
    /** 斯洛姆战鼓 */
    beastmaster_drums_of_slom = 'beastmaster_drums_of_slom',
    /** 瘴气 */
    venomancer_venomous_gale = 'venomancer_venomous_gale',
    /** 毒刺 */
    venomancer_poison_sting = 'venomancer_poison_sting',
    /** 瘟疫守卫 */
    venomancer_plague_ward = 'venomancer_plague_ward',
    /** 剧毒新星 */
    venomancer_poison_nova = 'venomancer_poison_nova',
    /** 蛰毒 */
    venomancer_latent_poison = 'venomancer_latent_poison',
    /** 恶性瘟疫 */
    venomancer_noxious_plague = 'venomancer_noxious_plague',
    /** 时间漫游 */
    faceless_void_time_walk = 'faceless_void_time_walk',
    /** 反时间漫游 */
    faceless_void_time_walk_reverse = 'faceless_void_time_walk_reverse',
    /** 时间膨胀 */
    faceless_void_time_dilation = 'faceless_void_time_dilation',
    /** 时间锁定 */
    faceless_void_time_lock = 'faceless_void_time_lock',
    /** 时间结界 */
    faceless_void_chronosphere = 'faceless_void_chronosphere',
    /** 地穴虫群 */
    death_prophet_carrion_swarm = 'death_prophet_carrion_swarm',
    /** 沉默魔法 */
    death_prophet_silence = 'death_prophet_silence',
    /** 吸魂巫术 */
    death_prophet_spirit_siphon = 'death_prophet_spirit_siphon',
    /** 驱使恶灵 */
    death_prophet_exorcism = 'death_prophet_exorcism',
    /** 幽冥爆轰 */
    pugna_nether_blast = 'pugna_nether_blast',
    /** 衰老 */
    pugna_decrepify = 'pugna_decrepify',
    /** 幽冥守卫 */
    pugna_nether_ward = 'pugna_nether_ward',
    /** 生命汲取 */
    pugna_life_drain = 'pugna_life_drain',
    /** 折光 */
    templar_assassin_refraction = 'templar_assassin_refraction',
    /** 隐匿 */
    templar_assassin_meld = 'templar_assassin_meld',
    /** 灵能之刃 */
    templar_assassin_psi_blades = 'templar_assassin_psi_blades',
    /** 灵能陷阱 */
    templar_assassin_psionic_trap = 'templar_assassin_psionic_trap',
    /** 触发陷阱 */
    templar_assassin_trap = 'templar_assassin_trap',
    /** 灵能投射 */
    templar_assassin_trap_teleport = 'templar_assassin_trap_teleport',
    /** 毒性攻击 */
    viper_poison_attack = 'viper_poison_attack',
    /** 幽冥剧毒 */
    viper_nethertoxin = 'viper_nethertoxin',
    /** 腐蚀皮肤 */
    viper_corrosive_skin = 'viper_corrosive_skin',
    /** 蝮蛇突袭 */
    viper_viper_strike = 'viper_viper_strike',
    /** 极恶俯冲 */
    viper_nose_dive = 'viper_nose_dive',
    /** 月光 */
    luna_lucent_beam = 'luna_lucent_beam',
    /** 月刃 */
    luna_moon_glaive = 'luna_moon_glaive',
    /** 月之祝福 */
    luna_lunar_blessing = 'luna_lunar_blessing',
    /** 月蚀 */
    luna_eclipse = 'luna_eclipse',
    /** 火焰气息 */
    dragon_knight_breathe_fire = 'dragon_knight_breathe_fire',
    /** 神龙摆尾 */
    dragon_knight_dragon_tail = 'dragon_knight_dragon_tail',
    /** 龙族血统 */
    dragon_knight_dragon_blood = 'dragon_knight_dragon_blood',
    /** 古龙形态 */
    dragon_knight_elder_dragon_form = 'dragon_knight_elder_dragon_form',
    /** 龙炎火球 */
    dragon_knight_fireball = 'dragon_knight_fireball',
    /** 真空 */
    dark_seer_vacuum = 'dark_seer_vacuum',
    /** 离子外壳 */
    dark_seer_ion_shell = 'dark_seer_ion_shell',
    /** 奔腾 */
    dark_seer_surge = 'dark_seer_surge',
    /** 复制之墙 */
    dark_seer_wall_of_replica = 'dark_seer_wall_of_replica',
    /** 普通一拳 */
    dark_seer_normal_punch = 'dark_seer_normal_punch',
    /** 炽烈火雨 */
    clinkz_burning_barrage = 'clinkz_burning_barrage',
    /** 焦油炸弹 */
    clinkz_tar_bomb = 'clinkz_tar_bomb',
    /** 扫射 */
    clinkz_strafe = 'clinkz_strafe',
    /** 骨隐步 */
    clinkz_wind_walk = 'clinkz_wind_walk',
    /** 死亡契约 */
    clinkz_death_pact = 'clinkz_death_pact',
    /** 烈焰之军 */
    clinkz_burning_army = 'clinkz_burning_army',
    /** 不可侵犯 */
    enchantress_untouchable = 'enchantress_untouchable',
    /** 魅惑 */
    enchantress_enchant = 'enchantress_enchant',
    /** 自然之助 */
    enchantress_natures_attendants = 'enchantress_natures_attendants',
    /** 推进 */
    enchantress_impetus = 'enchantress_impetus',
    /** 密友 */
    enchantress_little_friends = 'enchantress_little_friends',
    /** 跃动 */
    enchantress_bunny_hop = 'enchantress_bunny_hop',
    /** 洗礼 */
    omniknight_purification = 'omniknight_purification',
    /** 驱逐 */
    omniknight_martyr = 'omniknight_martyr',
    /** 守护天使 */
    omniknight_guardian_angel = 'omniknight_guardian_angel',
    /** 纯洁之锤 */
    omniknight_hammer_of_purity = 'omniknight_hammer_of_purity',
    /** 心炎 */
    huskar_inner_fire = 'huskar_inner_fire',
    /** 沸血之矛 */
    huskar_burning_spear = 'huskar_burning_spear',
    /** 狂战士之血 */
    huskar_berserkers_blood = 'huskar_berserkers_blood',
    /** 牺牲 */
    huskar_life_break = 'huskar_life_break',
    /** 虚空 */
    night_stalker_void = 'night_stalker_void',
    /** 伤残恐惧 */
    night_stalker_crippling_fear = 'night_stalker_crippling_fear',
    /** 暗夜猎影 */
    night_stalker_hunter_in_the_night = 'night_stalker_hunter_in_the_night',
    /** 黑暗飞升 */
    night_stalker_darkness = 'night_stalker_darkness',
    /** 孵化蜘蛛 */
    broodmother_spawn_spiderlings = 'broodmother_spawn_spiderlings',
    /** 蛛纱陷阱 */
    broodmother_sticky_snare = 'broodmother_sticky_snare',
    /** 织网 */
    broodmother_spin_web = 'broodmother_spin_web',
    /** 丝质重器 */
    broodmother_silken_bola = 'broodmother_silken_bola',
    /** 极度饥渴 */
    broodmother_insatiable_hunger = 'broodmother_insatiable_hunger',
    /** 投掷飞镖 */
    bounty_hunter_shuriken_toss = 'bounty_hunter_shuriken_toss',
    /** 忍术 */
    bounty_hunter_jinada = 'bounty_hunter_jinada',
    /** 暗影步 */
    bounty_hunter_wind_walk = 'bounty_hunter_wind_walk',
    /** 暗影情谊 */
    bounty_hunter_wind_walk_ally = 'bounty_hunter_wind_walk_ally',
    /** 追踪术 */
    bounty_hunter_track = 'bounty_hunter_track',
    /** 虫群 */
    weaver_the_swarm = 'weaver_the_swarm',
    /** 缩地 */
    weaver_shukuchi = 'weaver_shukuchi',
    /** 连击 */
    weaver_geminate_attack = 'weaver_geminate_attack',
    /** 时光倒流 */
    weaver_time_lapse = 'weaver_time_lapse',
    /** 冰火交加 */
    jakiro_dual_breath = 'jakiro_dual_breath',
    /** 冰封路径 */
    jakiro_ice_path = 'jakiro_ice_path',
    /** 液态火 */
    jakiro_liquid_fire = 'jakiro_liquid_fire',
    /** 液态冰 */
    jakiro_liquid_ice = 'jakiro_liquid_ice',
    /** 烈焰焚身 */
    jakiro_macropyre = 'jakiro_macropyre',
    /** 粘性燃油 */
    batrider_sticky_napalm = 'batrider_sticky_napalm',
    /** 施加时伤害： */
    batrider_sticky_napalm_application_damage = 'batrider_sticky_napalm_application_damage',
    /** 烈焰破击 */
    batrider_flamebreak = 'batrider_flamebreak',
    /** 火焰飞行 */
    batrider_firefly = 'batrider_firefly',
    /** 燃烧枷锁 */
    batrider_flaming_lasso = 'batrider_flaming_lasso',
    /** 赎罪 */
    chen_penitence = 'chen_penitence',
    /** 神力恩泽 */
    chen_divine_favor = 'chen_divine_favor',
    /** 神圣劝化 */
    chen_holy_persuasion = 'chen_holy_persuasion',
    /** 上帝之手 */
    chen_hand_of_god = 'chen_hand_of_god',
    /** 幽鬼之刃 */
    spectre_spectral_dagger = 'spectre_spectral_dagger',
    /** 荒芜 */
    spectre_desolate = 'spectre_desolate',
    /** 折射 */
    spectre_dispersion = 'spectre_dispersion',
    /** 鬼影重重 */
    spectre_haunt = 'spectre_haunt',
    /** 空降 */
    spectre_reality = 'spectre_reality',
    /** 如影随形 */
    spectre_haunt_single = 'spectre_haunt_single',
    /** 吞噬 */
    doom_bringer_devour = 'doom_bringer_devour',
    /** 焦土 */
    doom_bringer_scorched_earth = 'doom_bringer_scorched_earth',
    /** 阎刃 */
    doom_bringer_infernal_blade = 'doom_bringer_infernal_blade',
    /** 末日 */
    doom_bringer_doom = 'doom_bringer_doom',
    /** 技能（来自吞噬） */
    doom_bringer_empty1 = 'doom_bringer_empty1',
    /** 技能（来自吞噬） */
    doom_bringer_empty2 = 'doom_bringer_empty2',
    /** 寒霜之足 */
    ancient_apparition_cold_feet = 'ancient_apparition_cold_feet',
    /** 冰霜漩涡 */
    ancient_apparition_ice_vortex = 'ancient_apparition_ice_vortex',
    /** 极寒之触 */
    ancient_apparition_chilling_touch = 'ancient_apparition_chilling_touch',
    /** 冰晶爆轰 */
    ancient_apparition_ice_blast = 'ancient_apparition_ice_blast',
    /** 释放 */
    ancient_apparition_ice_blast_release = 'ancient_apparition_ice_blast_release',
    /** 震撼大地 */
    ursa_earthshock = 'ursa_earthshock',
    /** 超强力量 */
    ursa_overpower = 'ursa_overpower',
    /** 怒意狂击 */
    ursa_fury_swipes = 'ursa_fury_swipes',
    /** 激怒 */
    ursa_enrage = 'ursa_enrage',
    /** 火箭弹幕 */
    gyrocopter_rocket_barrage = 'gyrocopter_rocket_barrage',
    /** 追踪导弹 */
    gyrocopter_homing_missile = 'gyrocopter_homing_missile',
    /** 高射火炮 */
    gyrocopter_flak_cannon = 'gyrocopter_flak_cannon',
    /** 召唤飞弹 */
    gyrocopter_call_down = 'gyrocopter_call_down',
    /** 暗影冲刺 */
    spirit_breaker_charge_of_darkness = 'spirit_breaker_charge_of_darkness',
    /** 威吓 */
    spirit_breaker_bulldoze = 'spirit_breaker_bulldoze',
    /** 巨力重击 */
    spirit_breaker_greater_bash = 'spirit_breaker_greater_bash',
    /** 幽冥一击 */
    spirit_breaker_nether_strike = 'spirit_breaker_nether_strike',
    /** 位面空洞 */
    spirit_breaker_planar_pocket = 'spirit_breaker_planar_pocket',
    /** 酸性喷雾 */
    alchemist_acid_spray = 'alchemist_acid_spray',
    /** 投掷不稳定化合物 */
    alchemist_unstable_concoction_throw = 'alchemist_unstable_concoction_throw',
    /** 不稳定化合物 */
    alchemist_unstable_concoction = 'alchemist_unstable_concoction',
    /** 贪魔的贪婪 */
    alchemist_goblins_greed = 'alchemist_goblins_greed',
    /** 化学狂暴 */
    alchemist_chemical_rage = 'alchemist_chemical_rage',
    /** 腐蚀兵械 */
    alchemist_corrosive_weaponry = 'alchemist_corrosive_weaponry',
    /** 狂暴药剂 */
    alchemist_berserk_potion = 'alchemist_berserk_potion',
    /** 冰 */
    invoker_quas = 'invoker_quas',
    /** 雷 */
    invoker_wex = 'invoker_wex',
    /** 火 */
    invoker_exort = 'invoker_exort',
    /** 祈唤技能 */
    invoker_empty1 = 'invoker_empty1',
    /** 祈唤技能 */
    invoker_empty2 = 'invoker_empty2',
    /** 元素祈唤 */
    invoker_invoke = 'invoker_invoke',
    /** 急速冷却 */
    invoker_cold_snap = 'invoker_cold_snap',
    /** 幽灵漫步 */
    invoker_ghost_walk = 'invoker_ghost_walk',
    /** 强袭飓风 */
    invoker_tornado = 'invoker_tornado',
    /** 电磁脉冲 */
    invoker_emp = 'invoker_emp',
    /** 灵动迅捷 */
    invoker_alacrity = 'invoker_alacrity',
    /** 混沌陨石 */
    invoker_chaos_meteor = 'invoker_chaos_meteor',
    /** 阳炎冲击 */
    invoker_sun_strike = 'invoker_sun_strike',
    /** 熔炉精灵 */
    invoker_forge_spirit = 'invoker_forge_spirit',
    /** 寒冰之墙 */
    invoker_ice_wall = 'invoker_ice_wall',
    /** 超震声波 */
    invoker_deafening_blast = 'invoker_deafening_blast',
    /** 急速冷却（omg） */
    invoker_cold_snap_ad = 'invoker_cold_snap_ad',
    /** 幽灵漫步（omg） */
    invoker_ghost_walk_ad = 'invoker_ghost_walk_ad',
    /** 强袭飓风（omg） */
    invoker_tornado_ad = 'invoker_tornado_ad',
    /** 电磁脉冲（omg） */
    invoker_emp_ad = 'invoker_emp_ad',
    /** 灵动迅捷（omg） */
    invoker_alacrity_ad = 'invoker_alacrity_ad',
    /** 混沌陨石（omg） */
    invoker_chaos_meteor_ad = 'invoker_chaos_meteor_ad',
    /** 阳炎冲击（omg） */
    invoker_sun_strike_ad = 'invoker_sun_strike_ad',
    /** 熔炉精灵（omg） */
    invoker_forge_spirit_ad = 'invoker_forge_spirit_ad',
    /** 寒冰之墙（omg） */
    invoker_ice_wall_ad = 'invoker_ice_wall_ad',
    /** 超震声波（omg） */
    invoker_deafening_blast_ad = 'invoker_deafening_blast_ad',
    /** 奥术诅咒 */
    silencer_curse_of_the_silent = 'silencer_curse_of_the_silent',
    /** 智慧之刃 */
    silencer_glaives_of_wisdom = 'silencer_glaives_of_wisdom',
    /** 遗言 */
    silencer_last_word = 'silencer_last_word',
    /** 全领域静默 */
    silencer_global_silence = 'silencer_global_silence',
    /** 奥术天球 */
    obsidian_destroyer_arcane_orb = 'obsidian_destroyer_arcane_orb',
    /** 星体禁锢 */
    obsidian_destroyer_astral_imprisonment = 'obsidian_destroyer_astral_imprisonment',
    /** 精华变迁 */
    obsidian_destroyer_equilibrium = 'obsidian_destroyer_equilibrium',
    /** 神智之蚀 */
    obsidian_destroyer_sanity_eclipse = 'obsidian_destroyer_sanity_eclipse',
    /** 召狼 */
    lycan_summon_wolves = 'lycan_summon_wolves',
    /** 嗥叫 */
    lycan_howl = 'lycan_howl',
    /** 野性驱使 */
    lycan_feral_impulse = 'lycan_feral_impulse',
    /** 变身 */
    lycan_shapeshift = 'lycan_shapeshift',
    /** 饿狼撕咬 */
    lycan_wolf_bite = 'lycan_wolf_bite',
    /** 熊灵伙伴 */
    lone_druid_spirit_bear = 'lone_druid_spirit_bear',
    /** 灵魂链接 */
    lone_druid_spirit_link = 'lone_druid_spirit_link',
    /** 野蛮咆哮 */
    lone_druid_savage_roar = 'lone_druid_savage_roar',
    /** 真熊形态 */
    lone_druid_true_form = 'lone_druid_true_form',
    /** 雷霆一击 */
    brewmaster_thunder_clap = 'brewmaster_thunder_clap',
    /** 余烬佳酿 */
    brewmaster_cinder_brew = 'brewmaster_cinder_brew',
    /** 醉拳 */
    brewmaster_drunken_brawler = 'brewmaster_drunken_brawler',
    /** 元素分离 */
    brewmaster_primal_split = 'brewmaster_primal_split',
    /** 元素伙伴 */
    brewmaster_primal_companion = 'brewmaster_primal_companion',
    /** 崩裂禁锢 */
    shadow_demon_disruption = 'shadow_demon_disruption',
    /** 暗影剧毒 */
    shadow_demon_shadow_poison = 'shadow_demon_shadow_poison',
    /** 释放暗影毒 */
    shadow_demon_shadow_poison_release = 'shadow_demon_shadow_poison_release',
    /** 邪恶净化 */
    shadow_demon_demonic_purge = 'shadow_demon_demonic_purge',
    /** 邪恶净愈 */
    shadow_demon_demonic_cleanse = 'shadow_demon_demonic_cleanse',
    /** 散播 */
    shadow_demon_disseminate = 'shadow_demon_disseminate',
    /** 混乱之箭 */
    chaos_knight_chaos_bolt = 'chaos_knight_chaos_bolt',
    /** 实相裂隙 */
    chaos_knight_reality_rift = 'chaos_knight_reality_rift',
    /** 混沌一击 */
    chaos_knight_chaos_strike = 'chaos_knight_chaos_strike',
    /** 混沌之军 */
    chaos_knight_phantasm = 'chaos_knight_phantasm',
    /** 狗屎运 */
    ogre_magi_dumb_luck = 'ogre_magi_dumb_luck',
    /** 火焰爆轰 */
    ogre_magi_fireblast = 'ogre_magi_fireblast',
    /** 未精通的火焰爆轰 */
    ogre_magi_unrefined_fireblast = 'ogre_magi_unrefined_fireblast',
    /** 引燃 */
    ogre_magi_ignite = 'ogre_magi_ignite',
    /** 嗜血术 */
    ogre_magi_bloodlust = 'ogre_magi_bloodlust',
    /** 多重施法 */
    ogre_magi_multicast = 'ogre_magi_multicast',
    /** 烈火护盾 */
    ogre_magi_smash = 'ogre_magi_smash',
    /** 自然蔽护 */
    treant_natures_guise = 'treant_natures_guise',
    /** 自然卷握 */
    treant_natures_grasp = 'treant_natures_grasp',
    /** 寄生种子 */
    treant_leech_seed = 'treant_leech_seed',
    /** 活体护甲 */
    treant_living_armor = 'treant_living_armor',
    /** 疯狂生长 */
    treant_overgrowth = 'treant_overgrowth',
    /** 丛林之眼 */
    treant_eyes_in_the_forest = 'treant_eyes_in_the_forest',
    /** 地之束缚 */
    meepo_earthbind = 'meepo_earthbind',
    /** 忽悠 */
    meepo_poof = 'meepo_poof',
    /** 洗劫 */
    meepo_ransack = 'meepo_ransack',
    /** 分则能成 */
    meepo_divided_we_stand = 'meepo_divided_we_stand',
    /** 掘地 */
    meepo_petrify = 'meepo_petrify',
    /** 超大米波 */
    meepo_megameepo = 'meepo_megameepo',
    /** 超大米波摔扔 */
    meepo_megameepo_fling = 'meepo_megameepo_fling',
    /** 黄泉颤抖 */
    visage_grave_chill = 'visage_grave_chill',
    /** 灵魂超度 */
    visage_soul_assumption = 'visage_soul_assumption',
    /** 陵卫斗篷 */
    visage_gravekeepers_cloak = 'visage_gravekeepers_cloak',
    /** 召唤佣兽 */
    visage_summon_familiars = 'visage_summon_familiars',
    /** 石像形态 */
    visage_summon_familiars_stone_form = 'visage_summon_familiars_stone_form',
    /** 石像形态 */
    visage_stone_form_self_cast = 'visage_stone_form_self_cast',
    /** 静如古墓 */
    visage_silent_as_the_grave = 'visage_silent_as_the_grave',
    /** 腐朽 */
    undying_decay = 'undying_decay',
    /** 噬魂 */
    undying_soul_rip = 'undying_soul_rip',
    /** 墓碑 */
    undying_tombstone = 'undying_tombstone',
    /** 血肉傀儡 */
    undying_flesh_golem = 'undying_flesh_golem',
    /** 隔空取物 */
    rubick_telekinesis = 'rubick_telekinesis',
    /** 隔空取物着陆 */
    rubick_telekinesis_land = 'rubick_telekinesis_land',
    /** 隔空取物着陆 */
    rubick_telekinesis_land_self = 'rubick_telekinesis_land_self',
    /** 弱化能流 */
    rubick_fade_bolt = 'rubick_fade_bolt',
    /** 奥术至尊 */
    rubick_arcane_supremacy = 'rubick_arcane_supremacy',
    /** 技能窃取 */
    rubick_spell_steal = 'rubick_spell_steal',
    /** 窃取的魔法 */
    rubick_empty1 = 'rubick_empty1',
    /** 窃取的魔法 */
    rubick_empty2 = 'rubick_empty2',
    /** 风雷之击 */
    disruptor_thunder_strike = 'disruptor_thunder_strike',
    /** 恶念瞥视 */
    disruptor_glimpse = 'disruptor_glimpse',
    /** 动能力场 */
    disruptor_kinetic_field = 'disruptor_kinetic_field',
    /** 静态风暴 */
    disruptor_static_storm = 'disruptor_static_storm',
    /** 穿刺 */
    nyx_assassin_impale = 'nyx_assassin_impale',
    /** 尖刺外壳 */
    nyx_assassin_spiked_carapace = 'nyx_assassin_spiked_carapace',
    /** 复仇 */
    nyx_assassin_vendetta = 'nyx_assassin_vendetta',
    /** 钻地 */
    nyx_assassin_burrow = 'nyx_assassin_burrow',
    /** 现身 */
    nyx_assassin_unburrow = 'nyx_assassin_unburrow',
    /** 神智爆裂 */
    nyx_assassin_jolt = 'nyx_assassin_jolt',
    /** 镜像 */
    naga_siren_mirror_image = 'naga_siren_mirror_image',
    /** 诱捕 */
    naga_siren_ensnare = 'naga_siren_ensnare',
    /** 激流 */
    naga_siren_rip_tide = 'naga_siren_rip_tide',
    /** 海妖之歌 */
    naga_siren_song_of_the_siren = 'naga_siren_song_of_the_siren',
    /** 终止海妖之歌 */
    naga_siren_song_of_the_siren_cancel = 'naga_siren_song_of_the_siren_cancel',
    /** 捕捞 */
    naga_siren_reel_in = 'naga_siren_reel_in',
    /** 冲击波 */
    keeper_of_the_light_illuminate = 'keeper_of_the_light_illuminate',
    /** 释放冲击波 */
    keeper_of_the_light_illuminate_end = 'keeper_of_the_light_illuminate_end',
    /** 炎阳之缚 */
    keeper_of_the_light_radiant_bind = 'keeper_of_the_light_radiant_bind',
    /** 查克拉魔法 */
    keeper_of_the_light_chakra_magic = 'keeper_of_the_light_chakra_magic',
    /** 灵光 */
    keeper_of_the_light_will_o_wisp = 'keeper_of_the_light_will_o_wisp',
    /** 灵魂形态 */
    keeper_of_the_light_spirit_form = 'keeper_of_the_light_spirit_form',
    /** 召回 */
    keeper_of_the_light_recall = 'keeper_of_the_light_recall',
    /** 致盲之光 */
    keeper_of_the_light_blinding_light = 'keeper_of_the_light_blinding_light',
    /** 冲击波 */
    keeper_of_the_light_spirit_form_illuminate = 'keeper_of_the_light_spirit_form_illuminate',
    /** 释放冲击波 */
    keeper_of_the_light_spirit_form_illuminate_end = 'keeper_of_the_light_spirit_form_illuminate_end',
    /** 羁绊 */
    wisp_tether = 'wisp_tether',
    /** 断开连接 */
    wisp_tether_break = 'wisp_tether_break',
    /** 幽魂 */
    wisp_spirits = 'wisp_spirits',
    /** 拉近幽魂 */
    wisp_spirits_in = 'wisp_spirits_in',
    /** 拉远幽魂 */
    wisp_spirits_out = 'wisp_spirits_out',
    /** 过载 */
    wisp_overcharge = 'wisp_overcharge',
    /** 降临 */
    wisp_relocate = 'wisp_relocate',
    /** 黑暗契约 */
    slark_dark_pact = 'slark_dark_pact',
    /** 突袭 */
    slark_pounce = 'slark_pounce',
    /** 能量转移 */
    slark_essence_shift = 'slark_essence_shift',
    /** 暗影之舞 */
    slark_shadow_dance = 'slark_shadow_dance',
    /** 深海护罩 */
    slark_depth_shroud = 'slark_depth_shroud',
    /** 分裂箭 */
    medusa_split_shot = 'medusa_split_shot',
    /** 秘术异蛇 */
    medusa_mystic_snake = 'medusa_mystic_snake',
    /** 魔法护盾 */
    medusa_mana_shield = 'medusa_mana_shield',
    /** 石化凝视 */
    medusa_stone_gaze = 'medusa_stone_gaze',
    /** 冷血动物 */
    medusa_cold_blooded = 'medusa_cold_blooded',
    /** 狂战士之怒 */
    troll_warlord_berserkers_rage = 'troll_warlord_berserkers_rage',
    /** 旋风飞斧（远程） */
    troll_warlord_whirling_axes_ranged = 'troll_warlord_whirling_axes_ranged',
    /** 旋风飞斧（近战） */
    troll_warlord_whirling_axes_melee = 'troll_warlord_whirling_axes_melee',
    /** 热血战魂 */
    troll_warlord_fervor = 'troll_warlord_fervor',
    /** 战斗专注 */
    troll_warlord_battle_trance = 'troll_warlord_battle_trance',
    /** 马蹄践踏 */
    centaur_hoof_stomp = 'centaur_hoof_stomp',
    /** 双刃剑 */
    centaur_double_edge = 'centaur_double_edge',
    /** 反伤 */
    centaur_return = 'centaur_return',
    /** 奔袭冲撞 */
    centaur_stampede = 'centaur_stampede',
    /** 马到成功 */
    centaur_work_horse = 'centaur_work_horse',
    /** 便车 */
    centaur_mount = 'centaur_mount',
    /** 震荡波 */
    magnataur_shockwave = 'magnataur_shockwave',
    /** 授予力量 */
    magnataur_empower = 'magnataur_empower',
    /** 巨角冲撞 */
    magnataur_skewer = 'magnataur_skewer',
    /** 两极反转 */
    magnataur_reverse_polarity = 'magnataur_reverse_polarity',
    /** 长角抛物 */
    magnataur_horn_toss = 'magnataur_horn_toss',
    /** 死亡旋风 */
    shredder_whirling_death = 'shredder_whirling_death',
    /** 伐木锯链 */
    shredder_timber_chain = 'shredder_timber_chain',
    /** 活性护甲 */
    shredder_reactive_armor = 'shredder_reactive_armor',
    /** 锯齿飞轮 */
    shredder_chakram = 'shredder_chakram',
    /** 收回锯齿飞轮 */
    shredder_return_chakram = 'shredder_return_chakram',
    /** 锯齿飞轮（二） */
    shredder_chakram_2 = 'shredder_chakram_2',
    /** 收回锯齿飞轮（二） */
    shredder_return_chakram_2 = 'shredder_return_chakram_2',
    /** 喷火装置 */
    shredder_flamethrower = 'shredder_flamethrower',
    /** 粘稠鼻液 */
    bristleback_viscous_nasal_goo = 'bristleback_viscous_nasal_goo',
    /** 刺针扫射 */
    bristleback_quill_spray = 'bristleback_quill_spray',
    /** 钢毛后背 */
    bristleback_bristleback = 'bristleback_bristleback',
    /** 战意 */
    bristleback_warpath = 'bristleback_warpath',
    /** 毛团 */
    bristleback_hairball = 'bristleback_hairball',
    /** 寒冰碎片 */
    tusk_ice_shards = 'tusk_ice_shards',
    /** 雪球 */
    tusk_snowball = 'tusk_snowball',
    /** 雪球滚滚 */
    tusk_launch_snowball = 'tusk_launch_snowball',
    /** 摔角行家 */
    tusk_tag_team = 'tusk_tag_team',
    /** 海象神拳！ */
    tusk_walrus_punch = 'tusk_walrus_punch',
    /** 海象飞踢 */
    tusk_walrus_kick = 'tusk_walrus_kick',
    /** 天裔之盾 */
    skywrath_mage_shield_of_the_scion = 'skywrath_mage_shield_of_the_scion',
    /** 奥法鹰隼 */
    skywrath_mage_arcane_bolt = 'skywrath_mage_arcane_bolt',
    /** 震荡光弹 */
    skywrath_mage_concussive_shot = 'skywrath_mage_concussive_shot',
    /** 上古封印 */
    skywrath_mage_ancient_seal = 'skywrath_mage_ancient_seal',
    /** 神秘之耀 */
    skywrath_mage_mystic_flare = 'skywrath_mage_mystic_flare',
    /** 迷雾缠绕 */
    abaddon_death_coil = 'abaddon_death_coil',
    /** 无光之盾 */
    abaddon_aphotic_shield = 'abaddon_aphotic_shield',
    /** 魔霭诅咒 */
    abaddon_frostmourne = 'abaddon_frostmourne',
    /** 回光返照 */
    abaddon_borrowed_time = 'abaddon_borrowed_time',
    /** 回音重踏 */
    elder_titan_echo_stomp = 'elder_titan_echo_stomp',
    /** 灵体游魂 */
    elder_titan_ancestral_spirit = 'elder_titan_ancestral_spirit',
    /** 灵体游魂回归 */
    elder_titan_return_spirit = 'elder_titan_return_spirit',
    /** 移动灵体游魂 */
    elder_titan_move_spirit = 'elder_titan_move_spirit',
    /** 自然秩序 */
    elder_titan_natural_order = 'elder_titan_natural_order',
    /** 裂地沟壑 */
    elder_titan_earth_splitter = 'elder_titan_earth_splitter',
    /** 压倒性优势 */
    legion_commander_overwhelming_odds = 'legion_commander_overwhelming_odds',
    /** 强攻 */
    legion_commander_press_the_attack = 'legion_commander_press_the_attack',
    /** 勇气之霎 */
    legion_commander_moment_of_courage = 'legion_commander_moment_of_courage',
    /** 决斗 */
    legion_commander_duel = 'legion_commander_duel',
    /** 炎阳索 */
    ember_spirit_searing_chains = 'ember_spirit_searing_chains',
    /** 无影拳 */
    ember_spirit_sleight_of_fist = 'ember_spirit_sleight_of_fist',
    /** 烈火罩 */
    ember_spirit_flame_guard = 'ember_spirit_flame_guard',
    /** 激活残焰 */
    ember_spirit_activate_fire_remnant = 'ember_spirit_activate_fire_remnant',
    /** 残焰 */
    ember_spirit_fire_remnant = 'ember_spirit_fire_remnant',
    /** 巨石冲击 */
    earth_spirit_boulder_smash = 'earth_spirit_boulder_smash',
    /** 巨石翻滚 */
    earth_spirit_rolling_boulder = 'earth_spirit_rolling_boulder',
    /** 地磁之握 */
    earth_spirit_geomagnetic_grip = 'earth_spirit_geomagnetic_grip',
    /** 残岩 */
    earth_spirit_stone_caller = 'earth_spirit_stone_caller',
    /** 磁化 */
    earth_spirit_magnetize = 'earth_spirit_magnetize',
    /** 残岩魔咒 */
    earth_spirit_petrify = 'earth_spirit_petrify',
    /** 火焰风暴 */
    abyssal_underlord_firestorm = 'abyssal_underlord_firestorm',
    /** 怨念深渊 */
    abyssal_underlord_pit_of_malice = 'abyssal_underlord_pit_of_malice',
    /** 衰退光环 */
    abyssal_underlord_atrophy_aura = 'abyssal_underlord_atrophy_aura',
    /** 恶魔之扉 */
    abyssal_underlord_dark_portal = 'abyssal_underlord_dark_portal',
    /** 凤凰冲击 */
    phoenix_icarus_dive = 'phoenix_icarus_dive',
    /** 终止凤凰冲击 */
    phoenix_icarus_dive_stop = 'phoenix_icarus_dive_stop',
    /** 烈火精灵 */
    phoenix_fire_spirits = 'phoenix_fire_spirits',
    /** 发动烈火精灵 */
    phoenix_launch_fire_spirit = 'phoenix_launch_fire_spirit',
    /** 烈日炙烤 */
    phoenix_sun_ray = 'phoenix_sun_ray',
    /** 终止烈日炙烤 */
    phoenix_sun_ray_stop = 'phoenix_sun_ray_stop',
    /** 切换移动状态 */
    phoenix_sun_ray_toggle_move = 'phoenix_sun_ray_toggle_move',
    /** 超新星 */
    phoenix_supernova = 'phoenix_supernova',
    /** 倒影 */
    terrorblade_reflection = 'terrorblade_reflection',
    /** 惑幻 */
    terrorblade_conjure_image = 'terrorblade_conjure_image',
    /** 魔化 */
    terrorblade_metamorphosis = 'terrorblade_metamorphosis',
    /** 魂断 */
    terrorblade_sunder = 'terrorblade_sunder',
    /** 恐怖心潮 */
    terrorblade_terror_wave = 'terrorblade_terror_wave',
    /** 恶魔狂热 */
    terrorblade_demon_zeal = 'terrorblade_demon_zeal',
    /** 气运之末 */
    oracle_fortunes_end = 'oracle_fortunes_end',
    /** 命运敕令 */
    oracle_fates_edict = 'oracle_fates_edict',
    /** 涤罪之焰 */
    oracle_purifying_flames = 'oracle_purifying_flames',
    /** 虚妄之诺 */
    oracle_false_promise = 'oracle_false_promise',
    /** 天命之雨 */
    oracle_rain_of_destiny = 'oracle_rain_of_destiny',
    /** 感应地雷 */
    techies_land_mines = 'techies_land_mines',
    /** 爆破起飞！ */
    techies_suicide = 'techies_suicide',
    /** 粘性炸弹 */
    techies_sticky_bomb = 'techies_sticky_bomb',
    /** 活性电击 */
    techies_reactive_tazer = 'techies_reactive_tazer',
    /** 引爆电击 */
    techies_reactive_tazer_stop = 'techies_reactive_tazer_stop',
    /** 雷区标识 */
    techies_minefield_sign = 'techies_minefield_sign',
    /** 严寒烧灼 */
    winter_wyvern_arctic_burn = 'winter_wyvern_arctic_burn',
    /** 碎裂冲击 */
    winter_wyvern_splinter_blast = 'winter_wyvern_splinter_blast',
    /** 极寒之拥 */
    winter_wyvern_cold_embrace = 'winter_wyvern_cold_embrace',
    /** 寒冬诅咒 */
    winter_wyvern_winters_curse = 'winter_wyvern_winters_curse',
    /** 乱流 */
    arc_warden_flux = 'arc_warden_flux',
    /** 磁场 */
    arc_warden_magnetic_field = 'arc_warden_magnetic_field',
    /** 闪光幽魂 */
    arc_warden_spark_wraith = 'arc_warden_spark_wraith',
    /** 风暴双雄 */
    arc_warden_tempest_double = 'arc_warden_tempest_double',
    /** 丛林之舞 */
    monkey_king_tree_dance = 'monkey_king_tree_dance',
    /** 乾坤之跃 */
    monkey_king_primal_spring = 'monkey_king_primal_spring',
    /** 马上跃出 */
    monkey_king_primal_spring_early = 'monkey_king_primal_spring_early',
    /** 棒击大地 */
    monkey_king_boundless_strike = 'monkey_king_boundless_strike',
    /** 如意棒法 */
    monkey_king_jingu_mastery = 'monkey_king_jingu_mastery',
    /** 七十二变 */
    monkey_king_mischief = 'monkey_king_mischief',
    /** 变回原状 */
    monkey_king_untransform = 'monkey_king_untransform',
    /** 猴子猴孙 */
    monkey_king_wukongs_command = 'monkey_king_wukongs_command',
    /** 荆棘迷宫 */
    dark_willow_bramble_maze = 'dark_willow_bramble_maze',
    /** 暗影之境 */
    dark_willow_shadow_realm = 'dark_willow_shadow_realm',
    /** 诅咒王冠 */
    dark_willow_cursed_crown = 'dark_willow_cursed_crown',
    /** 恐吓 */
    dark_willow_terrorize = 'dark_willow_terrorize',
    /** 作祟 */
    dark_willow_bedlam = 'dark_willow_bedlam',
    /** 虚张声势 */
    pangolier_swashbuckle = 'pangolier_swashbuckle',
    /** 甲盾冲击 */
    pangolier_shield_crash = 'pangolier_shield_crash',
    /** 幸运一击 */
    pangolier_lucky_shot = 'pangolier_lucky_shot',
    /** 地雷滚滚 */
    pangolier_gyroshell = 'pangolier_gyroshell',
    /** 停止滚动 */
    pangolier_gyroshell_stop = 'pangolier_gyroshell_stop',
    /** 卷土重来 */
    pangolier_rollup = 'pangolier_rollup',
    /** 中止卷土重来 */
    pangolier_rollup_stop = 'pangolier_rollup_stop',
    /** 命运之笔 */
    grimstroke_dark_artistry = 'grimstroke_dark_artistry',
    /** 幻影之拥 */
    grimstroke_ink_creature = 'grimstroke_ink_creature',
    /** 爆墨 */
    grimstroke_return = 'grimstroke_return',
    /** 墨涌 */
    grimstroke_spirit_walk = 'grimstroke_spirit_walk',
    /** 缚魂 */
    grimstroke_soul_chain = 'grimstroke_soul_chain',
    /** 暗绘 */
    grimstroke_dark_portrait = 'grimstroke_dark_portrait',
    /** 战神迅矛 */
    mars_spear = 'mars_spear',
    /** 神之谴戒 */
    mars_gods_rebuke = 'mars_gods_rebuke',
    /** 护身甲盾 */
    mars_bulwark = 'mars_bulwark',
    /** 热血竞技场 */
    mars_arena_of_blood = 'mars_arena_of_blood',
    /** 残阴 */
    void_spirit_aether_remnant = 'void_spirit_aether_remnant',
    /** 异化 */
    void_spirit_dissimilate = 'void_spirit_dissimilate',
    /** 太虚之径 */
    void_spirit_astral_step = 'void_spirit_astral_step',
    /** 共鸣脉冲 */
    void_spirit_resonant_pulse = 'void_spirit_resonant_pulse',
    /** 电光石火 */
    snapfire_scatterblast = 'snapfire_scatterblast',
    /** 龙炎饼干 */
    snapfire_firesnap_cookie = 'snapfire_firesnap_cookie',
    /** 霹雳铁手 */
    snapfire_lil_shredder = 'snapfire_lil_shredder',
    /** 蜥蜴绝吻 */
    snapfire_mortimer_kisses = 'snapfire_mortimer_kisses',
    /** 血盆大口 */
    snapfire_gobble_up = 'snapfire_gobble_up',
    /** 喷吐 */
    snapfire_spit_creep = 'snapfire_spit_creep',
    /** 爆栗出击 */
    hoodwink_acorn_shot = 'hoodwink_acorn_shot',
    /** 野地奇袭 */
    hoodwink_bushwhack = 'hoodwink_bushwhack',
    /** 密林奔走 */
    hoodwink_scurry = 'hoodwink_scurry',
    /** 一箭穿心 */
    hoodwink_sharpshooter = 'hoodwink_sharpshooter',
    /** 中止一箭穿心 */
    hoodwink_sharpshooter_release = 'hoodwink_sharpshooter_release',
    /** 诱敌奇术 */
    hoodwink_decoy = 'hoodwink_decoy',
    /** 猎手旋镖 */
    hoodwink_hunters_boomerang = 'hoodwink_hunters_boomerang',
    /** 天光现世 */
    dawnbreaker_solar_guardian = 'dawnbreaker_solar_guardian',
    /** 天光现世落地 */
    dawnbreaker_land = 'dawnbreaker_land',
    /** 星破天惊 */
    dawnbreaker_fire_wreath = 'dawnbreaker_fire_wreath',
    /** 会合 */
    dawnbreaker_converge = 'dawnbreaker_converge',
    /** 上界重锤 */
    dawnbreaker_celestial_hammer = 'dawnbreaker_celestial_hammer',
    /** 熠熠生辉 */
    dawnbreaker_luminosity = 'dawnbreaker_luminosity',
    /** 过肩摔 */
    marci_grapple = 'marci_grapple',
    /** 怒拳破 */
    marci_unleash = 'marci_unleash',
    /** 回身踢 */
    marci_companion_run = 'marci_companion_run',
    /** 健体术 */
    marci_guardian = 'marci_guardian',
    /** 踏 */
    primal_beast_trample = 'primal_beast_trample',
    /** 捶 */
    primal_beast_pulverize = 'primal_beast_pulverize',
    /** 突 */
    primal_beast_onslaught = 'primal_beast_onslaught',
    /** 正在突进 */
    primal_beast_onslaught_release = 'primal_beast_onslaught_release',
    /** 砸 */
    primal_beast_rock_throw = 'primal_beast_rock_throw',
    /** 咤 */
    primal_beast_uproar = 'primal_beast_uproar',
    /** 弹无虚发 */
    muerta_dead_shot = 'muerta_dead_shot',
    /** 唤魂 */
    muerta_the_calling = 'muerta_the_calling',
    /** 越界 */
    muerta_pierce_the_veil = 'muerta_pierce_the_veil',
    /** 神枪在手 */
    muerta_gunslinger = 'muerta_gunslinger',
    /** 临别一枪 */
    muerta_parting_shot = 'muerta_parting_shot',
}
/** Dota原生英雄 */
declare const enum DotaHero {
    /** 敌法师 */
    antimage = 'npc_dota_hero_antimage',
    /** 痛苦女王 */
    queenofpain = 'npc_dota_hero_queenofpain',
    /** 莉娜 */
    lina = 'npc_dota_hero_lina',
    /** 米拉娜 */
    mirana = 'npc_dota_hero_mirana',
    /** 噬魂鬼 */
    life_stealer = 'npc_dota_hero_life_stealer',
    /** 先知 */
    furion = 'npc_dota_hero_furion',
    /** 风行者 */
    windrunner = 'npc_dota_hero_windrunner',
    /** 莱恩 */
    lion = 'npc_dota_hero_lion',
    /** 复仇之魂 */
    vengefulspirit = 'npc_dota_hero_vengefulspirit',
    /** 巫医 */
    witch_doctor = 'npc_dota_hero_witch_doctor',
    /** 拉席克 */
    leshrac = 'npc_dota_hero_leshrac',
    /** 主宰 */
    juggernaut = 'npc_dota_hero_juggernaut',
    /** 帕吉 */
    pudge = 'npc_dota_hero_pudge',
    /** 祸乱之源 */
    bane = 'npc_dota_hero_bane',
    /** 撼地者 */
    earthshaker = 'npc_dota_hero_earthshaker',
    /** 沙王 */
    sand_king = 'npc_dota_hero_sand_king',
    /** 影魔 */
    nevermore = 'npc_dota_hero_nevermore',
    /** 斯温 */
    sven = 'npc_dota_hero_sven',
    /** 幻影刺客 */
    phantom_assassin = 'npc_dota_hero_phantom_assassin',
    /** 冥魂大帝 */
    skeleton_king = 'npc_dota_hero_skeleton_king',
    /** 卓尔游侠 */
    drow_ranger = 'npc_dota_hero_drow_ranger',
    /** 变体精灵 */
    morphling = 'npc_dota_hero_morphling',
    /** 血魔 */
    bloodseeker = 'npc_dota_hero_bloodseeker',
    /** 斧王 */
    axe = 'npc_dota_hero_axe',
    /** 幻影长矛手 */
    phantom_lancer = 'npc_dota_hero_phantom_lancer',
    /** 雷泽 */
    razor = 'npc_dota_hero_razor',
    /** 风暴之灵 */
    storm_spirit = 'npc_dota_hero_storm_spirit',
    /** 水晶室女 */
    crystal_maiden = 'npc_dota_hero_crystal_maiden',
    /** 昆卡 */
    kunkka = 'npc_dota_hero_kunkka',
    /** 术士 */
    warlock = 'npc_dota_hero_warlock',
    /** 宙斯 */
    zuus = 'npc_dota_hero_zuus',
    /** 小小 */
    tiny = 'npc_dota_hero_tiny',
    /** 帕克 */
    puck = 'npc_dota_hero_puck',
    /** 戴泽 */
    dazzle = 'npc_dota_hero_dazzle',
    /** 发条技师 */
    rattletrap = 'npc_dota_hero_rattletrap',
    /** 巫妖 */
    lich = 'npc_dota_hero_lich',
    /** 潮汐猎人 */
    tidehunter = 'npc_dota_hero_tidehunter',
    /** 暗影萨满 */
    shadow_shaman = 'npc_dota_hero_shadow_shaman',
    /** 力丸 */
    riki = 'npc_dota_hero_riki',
    /** 谜团 */
    enigma = 'npc_dota_hero_enigma',
    /** 修补匠 */
    tinker = 'npc_dota_hero_tinker',
    /** 狙击手 */
    sniper = 'npc_dota_hero_sniper',
    /** 瘟疫法师 */
    necrolyte = 'npc_dota_hero_necrolyte',
    /** 斯拉达 */
    slardar = 'npc_dota_hero_slardar',
    /** 兽王 */
    beastmaster = 'npc_dota_hero_beastmaster',
    /** 剧毒术士 */
    venomancer = 'npc_dota_hero_venomancer',
    /** 虚空假面 */
    faceless_void = 'npc_dota_hero_faceless_void',
    /** 死亡先知 */
    death_prophet = 'npc_dota_hero_death_prophet',
    /** 帕格纳 */
    pugna = 'npc_dota_hero_pugna',
    /** 圣堂刺客 */
    templar_assassin = 'npc_dota_hero_templar_assassin',
    /** 冥界亚龙 */
    viper = 'npc_dota_hero_viper',
    /** 露娜 */
    luna = 'npc_dota_hero_luna',
    /** 龙骑士 */
    dragon_knight = 'npc_dota_hero_dragon_knight',
    /** 黑暗贤者 */
    dark_seer = 'npc_dota_hero_dark_seer',
    /** 克林克兹 */
    clinkz = 'npc_dota_hero_clinkz',
    /** 魅惑魔女 */
    enchantress = 'npc_dota_hero_enchantress',
    /** 全能骑士 */
    omniknight = 'npc_dota_hero_omniknight',
    /** 哈斯卡 */
    huskar = 'npc_dota_hero_huskar',
    /** 暗夜魔王 */
    night_stalker = 'npc_dota_hero_night_stalker',
    /** 育母蜘蛛 */
    broodmother = 'npc_dota_hero_broodmother',
    /** 赏金猎人 */
    bounty_hunter = 'npc_dota_hero_bounty_hunter',
    /** 编织者 */
    weaver = 'npc_dota_hero_weaver',
    /** 杰奇洛 */
    jakiro = 'npc_dota_hero_jakiro',
    /** 蝙蝠骑士 */
    batrider = 'npc_dota_hero_batrider',
    /** 陈 */
    chen = 'npc_dota_hero_chen',
    /** 幽鬼 */
    spectre = 'npc_dota_hero_spectre',
    /** 末日使者 */
    doom_bringer = 'npc_dota_hero_doom_bringer',
    /** 远古冰魄 */
    ancient_apparition = 'npc_dota_hero_ancient_apparition',
    /** 熊战士 */
    ursa = 'npc_dota_hero_ursa',
    /** 矮人直升机 */
    gyrocopter = 'npc_dota_hero_gyrocopter',
    /** 裂魂人 */
    spirit_breaker = 'npc_dota_hero_spirit_breaker',
    /** 炼金术士 */
    alchemist = 'npc_dota_hero_alchemist',
    /** 祈求者 */
    invoker = 'npc_dota_hero_invoker',
    /** 沉默术士 */
    silencer = 'npc_dota_hero_silencer',
    /** 殁境神蚀者 */
    obsidian_destroyer = 'npc_dota_hero_obsidian_destroyer',
    /** 狼人 */
    lycan = 'npc_dota_hero_lycan',
    /** 德鲁伊 */
    lone_druid = 'npc_dota_hero_lone_druid',
    /** 酒仙 */
    brewmaster = 'npc_dota_hero_brewmaster',
    /** 暗影恶魔 */
    shadow_demon = 'npc_dota_hero_shadow_demon',
    /** 混沌骑士 */
    chaos_knight = 'npc_dota_hero_chaos_knight',
    /** 食人魔魔法师 */
    ogre_magi = 'npc_dota_hero_ogre_magi',
    /** 树精卫士 */
    treant = 'npc_dota_hero_treant',
    /** 米波 */
    meepo = 'npc_dota_hero_meepo',
    /** 维萨吉 */
    visage = 'npc_dota_hero_visage',
    /** 不朽尸王 */
    undying = 'npc_dota_hero_undying',
    /** 拉比克 */
    rubick = 'npc_dota_hero_rubick',
    /** 干扰者 */
    disruptor = 'npc_dota_hero_disruptor',
    /** 司夜刺客 */
    nyx_assassin = 'npc_dota_hero_nyx_assassin',
    /** 娜迦海妖 */
    naga_siren = 'npc_dota_hero_naga_siren',
    /** 光之守卫 */
    keeper_of_the_light = 'npc_dota_hero_keeper_of_the_light',
    /** 艾欧 */
    wisp = 'npc_dota_hero_wisp',
    /** 斯拉克 */
    slark = 'npc_dota_hero_slark',
    /** 美杜莎 */
    medusa = 'npc_dota_hero_medusa',
    /** 巨魔战将 */
    troll_warlord = 'npc_dota_hero_troll_warlord',
    /** 半人马战行者 */
    centaur = 'npc_dota_hero_centaur',
    /** 马格纳斯 */
    magnataur = 'npc_dota_hero_magnataur',
    /** 伐木机 */
    shredder = 'npc_dota_hero_shredder',
    /** 钢背兽 */
    bristleback = 'npc_dota_hero_bristleback',
    /** 巨牙海民 */
    tusk = 'npc_dota_hero_tusk',
    /** 天怒法师 */
    skywrath_mage = 'npc_dota_hero_skywrath_mage',
    /** 亚巴顿 */
    abaddon = 'npc_dota_hero_abaddon',
    /** 上古巨神 */
    elder_titan = 'npc_dota_hero_elder_titan',
    /** 军团指挥官 */
    legion_commander = 'npc_dota_hero_legion_commander',
    /** 灰烬之灵 */
    ember_spirit = 'npc_dota_hero_ember_spirit',
    /** 大地之灵 */
    earth_spirit = 'npc_dota_hero_earth_spirit',
    /** 孽主 */
    abyssal_underlord = 'npc_dota_hero_abyssal_underlord',
    /** 凤凰 */
    phoenix = 'npc_dota_hero_phoenix',
    /** 恐怖利刃 */
    terrorblade = 'npc_dota_hero_terrorblade',
    /** 神谕者 */
    oracle = 'npc_dota_hero_oracle',
    /** 工程师 */
    techies = 'npc_dota_hero_techies',
    /** 寒冬飞龙 */
    winter_wyvern = 'npc_dota_hero_winter_wyvern',
    /** 天穹守望者 */
    arc_warden = 'npc_dota_hero_arc_warden',
    /** 齐天大圣 */
    monkey_king = 'npc_dota_hero_monkey_king',
    /** 邪影芳灵 */
    dark_willow = 'npc_dota_hero_dark_willow',
    /** 石鳞剑士 */
    pangolier = 'npc_dota_hero_pangolier',
    /** 天涯墨客 */
    grimstroke = 'npc_dota_hero_grimstroke',
    /** 玛尔斯 */
    mars = 'npc_dota_hero_mars',
    /** 虚无之灵 */
    void_spirit = 'npc_dota_hero_void_spirit',
    /** 电炎绝手 */
    snapfire = 'npc_dota_hero_snapfire',
    /** 森海飞霞 */
    hoodwink = 'npc_dota_hero_hoodwink',
    /** 破晓辰星 */
    dawnbreaker = 'npc_dota_hero_dawnbreaker',
    /** 玛西 */
    marci = 'npc_dota_hero_marci',
    /** 獸 */
    primal_beast = 'npc_dota_hero_primal_beast',
    /** 琼英碧灵 */
    muerta = 'npc_dota_hero_muerta',
}
/** Dota原生道具 */
declare const enum DotaItem {
    /** 深渊之刃 */
    abyssal_blade = 'item_abyssal_blade',
    /** 奥术指环 */
    arcane_ring = 'item_arcane_ring',
    /** 莫尔迪基安的臂章 */
    armlet = 'item_armlet',
    /** 强袭胸甲 */
    assault = 'item_assault',
    /** 碎颅锤 */
    basher = 'item_basher',
    /** 力量腰带 */
    belt_of_strength = 'item_belt_of_strength',
    /** 狂战斧 */
    bfury = 'item_bfury',
    /** 黑皇杖 */
    black_king_bar = 'item_black_king_bar',
    /** 刃甲 */
    blade_mail = 'item_blade_mail',
    /** 攻击之爪 */
    blades_of_attack = 'item_blades_of_attack',
    /** 欢欣之刃 */
    blade_of_alacrity = 'item_blade_of_alacrity',
    /** 闪烁匕首 */
    blink = 'item_blink',
    /** 血精石 */
    bloodstone = 'item_bloodstone',
    /** 速度之靴 */
    boots = 'item_boots',
    /** 精灵布带 */
    boots_of_elves = 'item_boots_of_elves',
    /** 魔瓶 */
    bottle = 'item_bottle',
    /** 护腕 */
    bracer = 'item_bracer',
    /** 铁树枝干 */
    branches = 'item_branches',
    /** 阔剑 */
    broadsword = 'item_broadsword',
    /** 玄冥盾牌 */
    buckler = 'item_buckler',
    /** 蝴蝶 */
    butterfly = 'item_butterfly',
    /** 锁子甲 */
    chainmail = 'item_chainmail',
    /** 圆环 */
    circlet = 'item_circlet',
    /** 王冠 */
    crown = 'item_crown',
    /** 净化药水 */
    clarity = 'item_clarity',
    /** 抗魔斗篷 */
    cloak = 'item_cloak',
    /** 仙灵之火 */
    faerie_fire = 'item_faerie_fire',
    /** 凝魂之露 */
    infused_raindrop = 'item_infused_raindrop',
    /** 风灵之纹 */
    wind_lace = 'item_wind_lace',
    /** 枯萎之石 */
    blight_stone = 'item_blight_stone',
    /** 魔龙枪 */
    dragon_lance = 'item_dragon_lance',
    /** 以太透镜 */
    aether_lens = 'item_aether_lens',
    /** 太虚之锤 */
    aetherial_halo = 'item_aetherial_halo',
    /** 大剑 */
    claymore = 'item_claymore',
    /** 陨星锤 */
    meteor_hammer = 'item_meteor_hammer',
    /** 否决坠饰 */
    nullifier = 'item_nullifier',
    /** 永恒之盘 */
    aeon_disk = 'item_aeon_disk',
    /** 慧光 */
    kaya = 'item_kaya',
    /** 散慧对剑 */
    kaya_and_sange = 'item_kaya_and_sange',
    /** 慧夜对剑 */
    yasha_and_kaya = 'item_yasha_and_kaya',
    /** 魂之灵瓮 */
    spirit_vessel = 'item_spirit_vessel',
    /** 赤红甲 */
    crimson_guard = 'item_crimson_guard',
    /** 风之杖 */
    wind_waker = 'item_wind_waker',
    /** eul的神圣法杖 */
    cyclone = 'item_cyclone',
    /** 达贡之神力 */
    dagon = 'item_dagon',
    /** 恶魔刀锋 */
    demon_edge = 'item_demon_edge',
    /** 黯灭 */
    desolator = 'item_desolator',
    /** 净魂之刃 */
    diffusal_blade = 'item_diffusal_blade',
    /** 显影之尘 */
    dust = 'item_dust',
    /** 鹰歌弓 */
    eagle = 'item_eagle',
    /** 能量之球 */
    energy_booster = 'item_energy_booster',
    /** 虚灵之刃 */
    ethereal_blade = 'item_ethereal_blade',
    /** 治疗药膏 */
    flask = 'item_flask',
    /** 原力法杖 */
    force_staff = 'item_force_staff',
    /** 力量手套 */
    gauntlets = 'item_gauntlets',
    /** 真视宝石 */
    gem = 'item_gem',
    /** 幽魂权杖 */
    ghost = 'item_ghost',
    /** 加速手套 */
    gloves = 'item_gloves',
    /** 代达罗斯之殇 */
    greater_crit = 'item_greater_crit',
    /** 迈达斯之手 */
    hand_of_midas = 'item_hand_of_midas',
    /** 恢复头巾 */
    headdress = 'item_headdress',
    /** 恐鳌之心 */
    heart = 'item_heart',
    /** 铁意头盔 */
    helm_of_iron_will = 'item_helm_of_iron_will',
    /** 支配头盔 */
    helm_of_the_dominator = 'item_helm_of_the_dominator',
    /** 统御头盔 */
    helm_of_the_overlord = 'item_helm_of_the_overlord',
    /** 挑战头巾 */
    hood_of_defiance = 'item_hood_of_defiance',
    /** 永世法衣 */
    eternal_shroud = 'item_eternal_shroud',
    /** 振奋宝石 */
    hyperstone = 'item_hyperstone',
    /** 影刃 */
    invis_sword = 'item_invis_sword',
    /** 白银之锋 */
    silver_edge = 'item_silver_edge',
    /** 微光披风 */
    glimmer_cape = 'item_glimmer_cape',
    /** 玲珑心 */
    octarine_core = 'item_octarine_core',
    /** 魔法芒果 */
    enchanted_mango = 'item_enchanted_mango',
    /** 清莲宝珠 */
    lotus_orb = 'item_lotus_orb',
    /** 卫士胫甲 */
    guardian_greaves = 'item_guardian_greaves',
    /** 炎阳纹章 */
    solar_crest = 'item_solar_crest',
    /** 标枪 */
    javelin = 'item_javelin',
    /** 水晶剑 */
    lesser_crit = 'item_lesser_crit',
    /** 吸血面具 */
    lifesteal = 'item_lifesteal',
    /** 巫毒面具 */
    voodoo_mask = 'item_voodoo_mask',
    /** 林肯法球 */
    sphere = 'item_sphere',
    /** 漩涡 */
    maelstrom = 'item_maelstrom',
    /** 魔棒 */
    magic_stick = 'item_magic_stick',
    /** 魔杖 */
    magic_wand = 'item_magic_wand',
    /** 幻影斧 */
    manta = 'item_manta',
    /** 智力斗篷 */
    mantle = 'item_mantle',
    /** 疯狂面具 */
    mask_of_madness = 'item_mask_of_madness',
    /** 梅肯斯姆 */
    mekansm = 'item_mekansm',
    /** 秘银锤 */
    mithril_hammer = 'item_mithril_hammer',
    /** 雷神之锤 */
    mjollnir = 'item_mjollnir',
    /** 金箍棒 */
    monkey_king_bar = 'item_monkey_king_bar',
    /** 神秘法杖 */
    mystic_staff = 'item_mystic_staff',
    /** 空灵挂件 */
    null_talisman = 'item_null_talisman',
    /** 飓风长戟 */
    hurricane_pike = 'item_hurricane_pike',
    /** 空明杖 */
    oblivion_staff = 'item_oblivion_staff',
    /** 巫师之刃 */
    witch_blade = 'item_witch_blade',
    /** 食人魔之斧 */
    ogre_axe = 'item_ogre_axe',
    /** 紫怨 */
    orchid = 'item_orchid',
    /** 血棘 */
    bloodthorn = 'item_bloodthorn',
    /** 坚韧球 */
    pers = 'item_pers',
    /** 相位鞋 */
    phase_boots = 'item_phase_boots',
    /** 洞察烟斗 */
    pipe = 'item_pipe',
    /** 板甲 */
    platemail = 'item_platemail',
    /** 精气之球 */
    point_booster = 'item_point_booster',
    /** 动力鞋 */
    power_treads = 'item_power_treads',
    /** 短棍 */
    quarterstaff = 'item_quarterstaff',
    /** 闪电指套 */
    blitz_knuckles = 'item_blitz_knuckles',
    /** 回音战刃 */
    echo_sabre = 'item_echo_sabre',
    /** 压制之刃 */
    quelling_blade = 'item_quelling_blade',
    /** 辉耀 */
    radiance = 'item_radiance',
    /** 圣剑 */
    rapier = 'item_rapier',
    /** 法师圣剑 */
    caster_rapier = 'item_caster_rapier',
    /** 掠夺者之斧 */
    reaver = 'item_reaver',
    /** 刷新球 */
    refresher = 'item_refresher',
    /** 圣者遗物 */
    relic = 'item_relic',
    /** 王者之戒 */
    ring_of_basilius = 'item_ring_of_basilius',
    /** 圣洁吊坠 */
    holy_locket = 'item_holy_locket',
    /** 治疗指环 */
    ring_of_health = 'item_ring_of_health',
    /** 守护指环 */
    ring_of_protection = 'item_ring_of_protection',
    /** 回复戒指 */
    ring_of_regen = 'item_ring_of_regen',
    /** 恐鳌之戒 */
    ring_of_tarrasque = 'item_ring_of_tarrasque',
    /** 法师长袍 */
    robe = 'item_robe',
    /** 阿托斯之棍 */
    rod_of_atos = 'item_rod_of_atos',
    /** 散华 */
    sange = 'item_sange',
    /** 天堂之戟 */
    heavens_halberd = 'item_heavens_halberd',
    /** 散夜对剑 */
    sange_and_yasha = 'item_sange_and_yasha',
    /** 撒旦之邪力 */
    satanic = 'item_satanic',
    /** 邪恶镰刀 */
    sheepstick = 'item_sheepstick',
    /** 希瓦的守护 */
    shivas_guard = 'item_shivas_guard',
    /** 斯嘉蒂之眼 */
    skadi = 'item_skadi',
    /** 敏捷便鞋 */
    slippers = 'item_slippers',
    /** 贤者面罩 */
    sobi_mask = 'item_sobi_mask',
    /** 振魂石 */
    soul_booster = 'item_soul_booster',
    /** 灵魂之戒 */
    soul_ring = 'item_soul_ring',
    /** 魔力法杖 */
    staff_of_wizardry = 'item_staff_of_wizardry',
    /** 圆盾 */
    stout_shield = 'item_stout_shield',
    /** 银月之晶 */
    moon_shard = 'item_moon_shard',
    /** 闪避护符 */
    talisman_of_evasion = 'item_talisman_of_evasion',
    /** 树之祭祀 */
    tango = 'item_tango',
    /** 回城卷轴 */
    tpscroll = 'item_tpscroll',
    /** 宽容之靴 */
    boots_of_bearing = 'item_boots_of_bearing',
    /** 静谧之鞋 */
    tranquil_boots = 'item_tranquil_boots',
    /** 远行鞋 */
    travel_boots = 'item_travel_boots',
    /** 极限法球 */
    ultimate_orb = 'item_ultimate_orb',
    /** 阿哈利姆神杖 */
    ultimate_scepter = 'item_ultimate_scepter',
    /** 阿哈利姆魔晶 */
    aghanims_shard = 'item_aghanims_shard',
    /** 影之灵龛 */
    urn_of_shadows = 'item_urn_of_shadows',
    /** 毛毛帽 */
    fluffy_hat = 'item_fluffy_hat',
    /** 猎鹰战刃 */
    falcon_blade = 'item_falcon_blade',
    /** 法师克星 */
    mage_slayer = 'item_mage_slayer',
    /** 盛势闪光 */
    overwhelming_blink = 'item_overwhelming_blink',
    /** 迅疾闪光 */
    swift_blink = 'item_swift_blink',
    /** 秘奥闪光 */
    arcane_blink = 'item_arcane_blink',
    /** 先锋盾 */
    vanguard = 'item_vanguard',
    /** 活力之球 */
    vitality_booster = 'item_vitality_booster',
    /** 弗拉迪米尔的祭品 */
    vladmir = 'item_vladmir',
    /** 虚无宝石 */
    void_stone = 'item_void_stone',
    /** 赛莉蒙妮之冠 */
    tiara_of_selemene = 'item_tiara_of_selemene',
    /** 侦察守卫 */
    ward_observer = 'item_ward_observer',
    /** 岗哨守卫 */
    ward_sentry = 'item_ward_sentry',
    /** 怨灵系带 */
    wraith_band = 'item_wraith_band',
    /** 夜叉 */
    yasha = 'item_yasha',
    /** 奥术鞋 */
    arcane_boots = 'item_arcane_boots',
    /** 淬毒之珠 */
    orb_of_venom = 'item_orb_of_venom',
    /** 韧鼓 */
    ancient_janggo = 'item_ancient_janggo',
    /** 诡计之雾 */
    smoke_of_deceit = 'item_smoke_of_deceit',
    /** 纷争面纱 */
    veil_of_discord = 'item_veil_of_discord',
    /** 英灵胸针 */
    revenants_brooch = 'item_revenants_brooch',
    /** 圣斧 */
    devastator = 'item_devastator',
    /** 天鹰之戒 */
    ring_of_aquila = 'item_ring_of_aquila',
    /** 暗影护符 */
    shadow_amulet = 'item_shadow_amulet',
    /** 基恩镜片 */
    keen_optic = 'item_keen_optic',
    /** 林野长弓 */
    grove_bow = 'item_grove_bow',
    /** 加速护符 */
    quickening_charm = 'item_quickening_charm',
    /** 贤者石 */
    philosophers_stone = 'item_philosophers_stone',
    /** 原力鞋 */
    force_boots = 'item_force_boots',
    /** 寂灭 */
    desolator_2 = 'item_desolator_2',
    /** 先哲之石 */
    seer_stone = 'item_seer_stone',
    /** 吸血鬼獠牙 */
    vampire_fangs = 'item_vampire_fangs',
    /** 崎岖外衣 */
    craggy_coat = 'item_craggy_coat',
    /** 永恒遗物 */
    timeless_relic = 'item_timeless_relic',
    /** 神镜盾 */
    mirror_shield = 'item_mirror_shield',
    /** 铁树之木 */
    ironwood_tree = 'item_ironwood_tree',
    /** 蜂王浆 */
    royal_jelly = 'item_royal_jelly',
    /** 学徒之礼 */
    pupils_gift = 'item_pupils_gift',
    /** 智灭 */
    mind_breaker = 'item_mind_breaker',
    /** 法术棱镜 */
    spell_prism = 'item_spell_prism',
    /** 亲王短刀 */
    princes_knife = 'item_princes_knife',
    /** 网虫腿 */
    spider_legs = 'item_spider_legs',
    /** 臂甲 */
    vambrace = 'item_vambrace',
    /** 魔童之爪 */
    imp_claw = 'item_imp_claw',
    /** 闪灵 */
    flicker = 'item_flicker',
    /** 望远镜 */
    spy_gadget = 'item_spy_gadget',
    /** 海洋之心 */
    ocean_heart = 'item_ocean_heart',
    /** 扫帚柄 */
    broom_handle = 'item_broom_handle',
    /** 可靠铁铲 */
    trusty_shovel = 'item_trusty_shovel',
    /** 幽冥披巾 */
    nether_shawl = 'item_nether_shawl',
    /** 炎龙之鳞 */
    dragon_scale = 'item_dragon_scale',
    /** 精华指环 */
    essence_ring = 'item_essence_ring',
    /** 魔力箭袋 */
    enchanted_quiver = 'item_enchanted_quiver',
    /** 忍者用具 */
    ninja_gear = 'item_ninja_gear',
    /** 幻术师披风 */
    illusionsts_cape = 'item_illusionsts_cape',
    /** 浩劫巨锤 */
    havoc_hammer = 'item_havoc_hammer',
    /** 神妙明灯 */
    panic_button = 'item_panic_button',
    /** 极 */
    apex = 'item_apex',
    /** 弩炮 */
    ballista = 'item_ballista',
    /** 冥灵书 */
    demonicon = 'item_demonicon',
    /** 天崩 */
    fallen_sky = 'item_fallen_sky',
    /** 海盗帽 */
    pirate_hat = 'item_pirate_hat',
    /** 机械之心 */
    ex_machina = 'item_ex_machina',
    /** 暗淡胸针 */
    faded_broach = 'item_faded_broach',
    /** 骑士剑 */
    paladin_sword = 'item_paladin_sword',
    /** 恶牛角 */
    minotaur_horn = 'item_minotaur_horn',
    /** 毁灭灵球 */
    orb_of_destruction = 'item_orb_of_destruction',
    /** 平世剑 */
    the_leveller = 'item_the_leveller',
    /** 巨神残铁 */
    titan_sliver = 'item_titan_sliver',
    /** 碎裂背心 */
    chipped_vest = 'item_chipped_vest',
    /** 腐蚀之球 */
    orb_of_corrosion = 'item_orb_of_corrosion',
    /** 精灵外衣 */
    elven_tunic = 'item_elven_tunic',
    /** 火焰斗篷 */
    cloak_of_flames = 'item_cloak_of_flames',
    /** 欺诈师斗篷 */
    trickster_cloak = 'item_trickster_cloak',
    /** 附魂面具 */
    possessed_mask = 'item_possessed_mask',
    /** 秘术师铠甲 */
    force_field = 'item_force_field',
    /** 雷火弹 */
    black_powder_bag = 'item_black_powder_bag',
    /** 简朴短帽 */
    ascetic_cap = 'item_ascetic_cap',
    /** 刚毅指环 */
    fortitude_ring = 'item_fortitude_ring',
    /** 杂技玩具 */
    pogo_stick = 'item_pogo_stick',
    /** 仙灵榴弹 */
    paintball = 'item_paintball',
    /** 行巫之祸 */
    heavy_blade = 'item_heavy_blade',
    /** 豚杆 */
    unstable_wand = 'item_unstable_wand',
    /** 伊卡洛斯之翼 */
    icarus_wings = 'item_icarus_wings',
    /** 飞贼之刃 */
    misericorde = 'item_misericorde',
    /** 风暴宝器 */
    stormcrafter = 'item_stormcrafter',
    /** 仙灵饰品 */
    mysterious_hat = 'item_mysterious_hat',
    /** 五锋长剑 */
    penta_edged_sword = 'item_penta_edged_sword',
    /** 缚灵索 */
    gungir = 'item_gungir',
    /** 通灵头带 */
    psychic_headband = 'item_psychic_headband',
    /** 祭礼长袍 */
    ceremonial_robe = 'item_ceremonial_robe',
    /** 暗影邪典 */
    book_of_shadows = 'item_book_of_shadows',
    /** 巨人之戒 */
    giants_ring = 'item_giants_ring',
    /** 复仇之影 */
    vengeances_shadow = 'item_vengeances_shadow',
    /** 凌厉长鞭 */
    bullwhip = 'item_bullwhip',
    /** 银闪护符 */
    quicksilver_amulet = 'item_quicksilver_amulet',
    /** 宁静种籽 */
    seeds_of_serenity = 'item_seeds_of_serenity',
    /** 追击之矛 */
    lance_of_pursuit = 'item_lance_of_pursuit',
    /** 玄奥手镯 */
    occult_bracelet = 'item_occult_bracelet',
    /** 食人魔海豹图腾 */
    ogre_seal_totem = 'item_ogre_seal_totem',
    /** 维齐尔之眼 */
    eye_of_the_vizier = 'item_eye_of_the_vizier',
    /** 行家阵列 */
    specialists_array = 'item_specialists_array',
    /** 瑞斯图尔尖匕 */
    dagger_of_ristul = 'item_dagger_of_ristul',
    /** 散魂剑 */
    disperser = 'item_disperser',
    /** 鱼叉 */
    harpoon = 'item_harpoon',
    /** 灵匣 */
    phylactery = 'item_phylactery',
    /** 绝刃 */
    angels_demise = 'item_angels_demise',
    /** 宝冕 */
    diadem = 'item_diadem',
    /** 不羁甲壳 */
    defiant_shell = 'item_defiant_shell',
    /** 血腥榴弹 */
    blood_grenade = 'item_blood_grenade',
    /** 勇气之光 */
    spark_of_courage = 'item_spark_of_courage',
    /** 荒芜之魂 */
    blighted_spirit = 'item_blighted_spirit',
    /** 决斗家手套 */
    duelist_gloves = 'item_duelist_gloves',
    /** 遗迹守护者 */
    ancient_guardian = 'item_ancient_guardian',
    /** 视界平衡 */
    horizons_equilibrium = 'item_horizons_equilibrium',
    /** 蒲公英护符 */
    dandelion_amulet = 'item_dandelion_amulet',
    /** 安全泡泡 */
    safety_bubble = 'item_safety_bubble',
    /** 邪道私语 */
    whisper_of_the_dread = 'item_whisper_of_the_dread',
    /** 天诛之咒 */
    nemesis_curse = 'item_nemesis_curse',
    /** 艾维娜之羽 */
    avianas_feather = 'item_avianas_feather',
    /** 坚毅之件 */
    unwavering_condition = 'item_unwavering_condition',
    /** 正义之斧 */
    vindicators_axe = 'item_vindicators_axe',
    /** 烈士鳞甲 */
    martyrs_plate = 'item_martyrs_plate',
    /** 丰饶之环 */
    cornucopia = 'item_cornucopia',
    /** 长盾 */
    pavise = 'item_pavise',
    /** 蛛丝斗篷 */
    gossamer_cape = 'item_gossamer_cape',
    /** 集光器 */
    light_collector = 'item_light_collector',
    /** 回响之笼 */
    rattlecage = 'item_rattlecage',
    /** 双面币 */
    doubloon = 'item_doubloon',
    /** 第一级代币 */
    item_tier1_token = 'item_tier1_token',
    /** 第二级代币 */
    item_tier2_token = 'item_tier2_token',
    /** 第三级代币 */
    item_tier3_token = 'item_tier3_token',
    /** 第四级代币 */
    item_tier4_token = 'item_tier4_token',
    /** 第五级代币 */
    item_tier5_token = 'item_tier5_token',
    /** 不朽之守护 */
    aegis = 'item_aegis',
}
